/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    LocaleSwitch: typeof import('./../components/LocaleSwitch.vue')['default']
    PopupNavbar: typeof import('./../components/popup/Navbar.vue')['default']
    PopupRecordsList: typeof import('./../components/popup/RecordsList.vue')['default']
    PopupSearchBar: typeof import('./../components/popup/SearchBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UiButtonButton: typeof import('./../components/ui/button/Button.vue')['default']
    UiDropdownMenuDropdownMenu: typeof import('./../components/ui/dropdown-menu/DropdownMenu.vue')['default']
    UiDropdownMenuDropdownMenuCheckboxItem: typeof import('./../components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    UiDropdownMenuDropdownMenuContent: typeof import('./../components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    UiDropdownMenuDropdownMenuGroup: typeof import('./../components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    UiDropdownMenuDropdownMenuItem: typeof import('./../components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    UiDropdownMenuDropdownMenuLabel: typeof import('./../components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    UiDropdownMenuDropdownMenuRadioGroup: typeof import('./../components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    UiDropdownMenuDropdownMenuRadioItem: typeof import('./../components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    UiDropdownMenuDropdownMenuSeparator: typeof import('./../components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    UiDropdownMenuDropdownMenuShortcut: typeof import('./../components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    UiDropdownMenuDropdownMenuSub: typeof import('./../components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    UiDropdownMenuDropdownMenuSubContent: typeof import('./../components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    UiDropdownMenuDropdownMenuSubTrigger: typeof import('./../components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    UiDropdownMenuDropdownMenuTrigger: typeof import('./../components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
  }
}
